/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        'tutorial/concepts',
        'tutorial/prerequisites',
        'tutorial/installation',
        'tutorial/test-pipeline',
        'tutorial/instrument',
        'tutorial/experiment',
        'tutorial/business',
      ],
    }
  ],
  referenceSidebar: [{type: 'autogenerated', dirName: 'reference'}],
};

export default sidebars;
